#!/usr/bin/env bash
# One-time bootstrap for the MonitorERP-KB app stack.
#
# Creates kb/.env (gitignored — credentials never committed) and starts the
# stack. Safe to re-run: an existing .env is left untouched.
#
# Interactive: RAGFLOW_API_KEY / RAGFLOW_DATASET_ID / RAGFLOW_AGENT_ID exist
# only in the RagFlow UI (created by you) — the script never generates or
# defaults them, it fails loudly instead (same spirit as the release gate).
#
# Requires: docker + docker compose, openssl (for secret generation).
# Must run on the server (this box), after ship-images.ps1 has shipped the
# images and postgres/bootstrap.sh has created postgres/.env (this stack
# reuses the server-level Postgres — its credentials live there, not here).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  echo "$ENV_FILE already exists — leaving it untouched."
  exit 0
fi

# --- DB credentials come from the server Postgres bootstrap ------------------
POSTGRES_ENV="$SCRIPT_DIR/../postgres/.env"
if [ ! -f "$POSTGRES_ENV" ]; then
  echo "ERROR: $POSTGRES_ENV not found." >&2
  echo "  Run ./postgres/bootstrap.sh first — the KB stack reuses the server" >&2
  echo "  Postgres and its credentials only exist in that file." >&2
  exit 1
fi
# shellcheck disable=SC1090
. "$POSTGRES_ENV"
POSTGRES_USER="${POSTGRES_USER:?missing POSTGRES_USER in $POSTGRES_ENV}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:?missing POSTGRES_PASSWORD in $POSTGRES_ENV}"
POSTGRES_DB="${POSTGRES_DB:?missing POSTGRES_DB in $POSTGRES_ENV}"
# The password was generated by postgres/bootstrap.sh as hex — URL-safe, no
# percent-encoding needed.
DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}"

# --- RagFlow credentials: only you have these — prompt, never invent ---------
echo "Enter the RagFlow credentials for MonitorERP-KB (from the RagFlow UI):"
read -r -p "  RAGFLOW_API_KEY (API keys page): " RAGFLOW_API_KEY
read -r -p "  RAGFLOW_DATASET_ID (Datasets page, dataset id): " RAGFLOW_DATASET_ID
read -r -p "  RAGFLOW_AGENT_ID (Agents page, agent id): " RAGFLOW_AGENT_ID
for var in RAGFLOW_API_KEY RAGFLOW_DATASET_ID RAGFLOW_AGENT_ID; do
  value="${!var}"
  if [ -z "$value" ]; then
    echo "ERROR: $var is required — run this script interactively, do not pipe input." >&2
    exit 1
  fi
  # RagFlow keys/ids are alphanumeric tokens; anything else is a paste mistake.
  case "$value" in
    *[^A-Za-z0-9._-]*)
      echo "ERROR: $var contains characters that cannot be right ($value)." >&2
      echo "  Expected an alphanumeric key/id from the RagFlow UI." >&2
      exit 1
      ;;
  esac
done

read -r -p "  KB_TAG (image tag for kb-api/kb-web, e.g. v0.1.0) [v0.1.0]: " KB_TAG
KB_TAG="${KB_TAG:-v0.1.0}"
case "$KB_TAG" in
  *[^A-Za-z0-9._-]*)
    echo "ERROR: KB_TAG must look like a git tag (e.g. v0.1.0), got: $KB_TAG" >&2
    exit 1
    ;;
esac

# --- generate the rest -------------------------------------------------------
JWT_SECRET="$(openssl rand -hex 32)"
ADMIN_EMAIL="admin@monitorerp.cn"
ADMIN_PASSWORD="$(openssl rand -hex 12)"
ADMIN_NAME="MonitorERP Admin"
RAGFLOW_URL="http://host.docker.internal:8080"
PORT="4801"
POLL_INTERVAL_MS="5000"

cat > "$ENV_FILE" <<EOF
KB_TAG=$KB_TAG
DATABASE_URL=$DATABASE_URL
JWT_SECRET=$JWT_SECRET
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_PASSWORD=$ADMIN_PASSWORD
ADMIN_NAME=$ADMIN_NAME
RAGFLOW_URL=$RAGFLOW_URL
RAGFLOW_API_KEY=$RAGFLOW_API_KEY
RAGFLOW_DATASET_ID=$RAGFLOW_DATASET_ID
RAGFLOW_AGENT_ID=$RAGFLOW_AGENT_ID
POLL_INTERVAL_MS=$POLL_INTERVAL_MS
PORT=$PORT
EOF
chmod 600 "$ENV_FILE"
echo "Created $ENV_FILE."

echo
echo "  >>> IMPORTANT — write the admin password down now:"
echo
echo "      admin email: $ADMIN_EMAIL"
echo "      admin name:  $ADMIN_NAME"
echo "      password:    $ADMIN_PASSWORD"
echo
echo "  The API seeds the super admin only while the users table is empty"
echo "  (first init). This password is valid exactly once — a regenerated"
echo "  .env's password is silently ignored afterwards."

(cd "$SCRIPT_DIR" && docker compose up -d)
echo
echo "KB stack is starting. Verify with: ./manage.sh status"
echo "  web:  https://kb.ai.monitorsystem.cn  (sign in with the password above)"
